export const Ammo = [
  // Ballistic
  ".308 round",
  ".38 round",
  ".44 round",
  ".45 round",
  ".50 caliber ball",
  ".50 round",
  "10mm round",
  "5.56 round",
  "5mm round",
  "Arrow",
  "Cannonball",
  "Crossbow bolt",
  "Shotgun shell",
  "Railway spike",

  // Explosive
  "40mm grenade round",
  "Mini nuke",
  "Missile",

  // Energy
  "2mm electromagnetic cartridge",
  "Alien blaster round",
  "Cryo cell",
  "Fuel",
  "Fusion cell",
  "Fusion core",
  "Gamma round",
  "Plasma cartridge",
  "Plasma core",

  // Ultracite
  "Ultracite .308 round",
  "Ultracite .38 round",
  "Ultracite .44 round",
  "Ultracite .45 round",
  "Ultracite .50 round",
  "Ultracite 10mm round",
  "Ultracite 5.56 round",
  "Ultracite 5mm round",
  "Ultracite arrow",
  "Ultracite crossbow bolt",
  "Ultracite shotgun shell",
  "Ultracite railway spike",
  "Ultracite 2mm electromagnetic cartridge",
  "Ultracite fusion cell",
  "Ultracite fusion core",
  "Ultracite plasma cartridge",
  "Ultracite plasma core",

  // Misc
  "Camera film",
  "Squirt of water",
  "Modified bowling ball",
];

export const Consumables_Aid = [
  "Addictol",
  "Antibiotics",
  "Berry Mentats",
  "Blood pack",
  "Buffout",
  "Bufftats",
  "Calmex",
  "Daddy-O",
  "Day Tripper",
  "Disease cure",
  "Formula P",
  "Fury",
  "Glowing blood",
  "Glowing blood pack",
  "Grape Mentats",
  "Healing salve",
  "Insect repellent",
  "Irradiated blood pack",
  "Med-X",
  "Mentats",
  "Nuclear Don's Custom Chem Blend",
  "Nuka-Cola My Blood's In It",
  "Nuka-Cola Scorched",
  "Nuka-Cola Vaccinated",
  "Orange Mentats",
  "Overdrive",
  "Psycho",
  "Psychobuff",
  "Psychotats",
  "Rad-X",
  "Rad-X: diluted",
  "RadAway",
  "RadAway: diluted",
  "RadShield",
  "Skeeto Spit",
  "Stimpak",
  "Stimpak diffuser",
  "Stimpak: diluted",
  "Stimpak: super",
  "Super chem Mk I",
  "Survival syringe",
  "X-cell",
];

export const Consumables_Drink = [
  "Nuka-Cola",
  "Nuka-Cola Quantum",
  "Nuka-Cherry",
  "Nuka-Cola Cranberry",
  "Nuka-Cola Dark",
  "Nuka-Cola Orange",
  "Nuka-Cola Twist",
  "Nuka-Cola Wild",
  "Nuka-Grape",
  "Hard Lemonade",
  "Canned coffee",
  "Hotdog",
  "Perfectly preserved pie",
];

export const Consumables_Misc = [
  "Bubblegum",
  "Stealth Boy",
  "Stealth Boy Mark III",
];

export const Mods = {
  weapon: {
    "1★": [
      "Anti-Armor",
      "Aristocrat's",
      "Assassin's",
      "Berserker's",
      "Bloodied",
      "Executioner's",
      "Exterminator's",
      "Furious",
      "Ghoul Slayer's",
      "Gourmand's",
      "Hunter's",
      "Instigating",
      "Juggernaut's",
      "Junkie's",
      "Medic's",
      "Mutant Slayer's",
      "Mutant's",
      "Nocturnal",
      "Quad",
      "Stalker's",
      "Suppressor's",
      "Troubleshooter's",
      "Two Shot",
      "Vampire's",
      "Zealot's",
    ],

    "2★": [
      "Explosive",
      "Rapid",
      "Hitman's",
      "Last Shot",
      "V.A.T.S. Enhanced",
      "Crippling",
      "Basher's",
      "Inertial",
      "Steady",
    ],

    "3★": ["Durability", "Lucky", "Swift", "V.A.T.S. Optimized", "Lightweight"],

    "4★": [
      "Pin-Pointer's",
      "Pounder's",
      "Polished",
      "Bruiser's",
      "Bully's",
      "Limit-Breaking",
      "Viper's",
    ],
    "Non legendary": ["Enclave flamer barrel"],
  },

  armor: {
    "1★": [
      "Auto Stim",
      "Bolstering",
      "Chameleon",
      "Cloaking",
      "Life Saving",
      "Mutant's",
      "Nocturnal",
      "Overeater's",
      "Regenerating",
      "Unyielding",
      "Vanguard's",
      "Weightless",
    ],

    "2★": [
      "Agility",
      "Charisma",
      "Endurance",
      "Intelligence",
      "Luck",
      "Perception",
      "Strength",
      "Powered",
      "Poisoner's",
      "Fireproof",
      "Hardy",
      "Glutton",
    ],

    "3★": [
      "Acrobat's",
      "Cavalier's",
      "Sentinel's",
      "Diver's",
      "Doctor's",
      "Arms Keeper's",
      "Belted",
    ],

    "4★": [
      "Aegis",
      "Tanky's",
      "Stalwart's",
      "Runner's",
      "Scanner's",
      "Sawbones's",
    ],
    "Non legendary": ["Aegis"],
  },
};

export const FurniturePlans = [
  "Acoustic instruments",
  "Advanced power connectors",
  "Antique tables",
  "Antique wooden chairs",
  "Armco ammunition construction appliance",
  "Backyard grill",
  "Ballistic weave",
  "Barn building set",
  "Baseball player statue",
  "Basic power connectors",
  "Bear-proof trashcan",
  "Beer keg",
  "Bistro set",
  "Bookcase",
  "Brass instruments",
  "Brewing station",
  "Brick building set",
  "Cabinets",
  "Campfire tales tent",
  "Cardboard standees",
  "Ceiling lights",
  "Chemistry workbench",
  "Circus cage trailer",
  "Circus bench",
  "Classic jack o'lantern",
  "Cooler",
  "Cooking stove",
  "Contemporary building set",
  "Concrete building set",
  "Display cases",
  "Domestic kitchen tables",
  "Dresser",
  "Electric chair",
  "Eat-O-Tronic",
  "Fasnacht decorations",
  "Filing cabinets",
  "Fire hydrant",
  "Floor decorations",
  "Floor safe",
  "Garden benches",
  "Garden lights",
  "Garage door",
  "Gas signs",
  "Greek letters set",
  "Halloween decorations",
  "Heavy turrets",
  "Holiday wreath",
  "Industrial water purifier",
  "Instruments",
  "Jack o'lantern set",
  "Lawn flamingos",
  "Metal building set",
  "Metal picnic table",
  "Military cot",
  "Mounted animal heads",
  "Neon letters",
  "Nuka-Cola machine",
  "Nuka-Cola signs",
  "Park benches",
  "Patio furniture",
  "Picnic tables",
  "Portable toilet",
  "Power armor station",
  "Radiation emitter",
  "Rugs",
  "Santa crash",
  "Security baton rack",
  "Shelves",
  "Signs and letters",
  "Sleeping bags",
  "Small letters set",
  "Statues",
  "String lights",
  "Suitcases",
  "Tables",
  "Thanksgiving display case",
  "Tool chest",
  "Track lighting",
  "Trash cans",
  "Turret platforms",
  "Utility wall shelves",
  "Vending machines",
  "Wall decorations",
  "Wall safes",
  "Welcome mats",
  "Wind instruments",
  "Wooden desks",
  "Wooden picnic table",
  "Wooden rocking chairs",
  "Wooden shelves",
  "Wooden stash box",
  "Workbenches",
  "Xylophone",
];

export const Blueprints = [
  // Food
  "Brain bombs",
  "Cranberry relish",
  "Grilled radstag",
  "Pepperoni roll",
  "Radstag stew",
  "S'mores",
  "Smoked mirelurk fillets",
  "Tasty squirrel stew",
  "Tasty stingwing stew",
  "Tato salad",
  "Vegetable soup",
  "Yao guai ribs",

  // Chems & Aid
  "Addictol",
  "Antibiotics",
  "Berry Mentats",
  "Bufftats",
  "Calmex",
  "Disease cure",
  "Fury",
  "Grape Mentats",
  "Healing salve",
  "Med-X",
  "Mentats",
  "Orange Mentats",
  "Overdrive",
  "Psycho",
  "Psychobuff",
  "Psychotats",
  "RadAway",
  "RadAway: diluted",
  "Rad-X",
  "Rad-X: diluted",
  "Skeeto Spit",
  "Stimpak",
  "Stimpak: diluted",
  "Stimpak: super",
  "X-Cell",

  // Brewing / Alcohol
  "Blackwater Brew",
  "Cranberry Moonshine",
  "Hard Lemonade",
  "Lead Champagne",
  "Lead Champagne Bellini",
  "Lead Champagne Mimosa",
  "Mountain Honey Moonshine",
  "New River Red Ale",
  "Oak Holler Lager",
  "Pickaxe Pilsner",
  "Tick blood tequila",
  "Tick blood tequila margarita",
  "Vintage nukashine",

  // Serums
  "Adrenal Reaction Serum",
  "Bird Bones Serum",
  "Carnivore Serum",
  "Chameleon Serum",
  "Eagle Eyes Serum",
  "Egg Head Serum",
  "Electrically Charged Serum",
  "Grounded Serum",
  "Healing Factor Serum",
  "Herbivore Serum",
  "Marsupial Serum",
  "Plague Walker Serum",
  "Speed Demon Serum",
  "Talons Serum",
  "Twisted Muscles Serum",
  "Unstable Isotope Serum",
];

export const Caps = ["Caps"];
export const Leaders = ["Leaders"];
export const Fuel = ["Fuel"];
